### ISSUE TITLE
[HyperShift] Gather must-gather from each Hosted Cluster

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/osde2e-scale-wrapper#101]
We need a must-gather from each Hosted Cluster after the churn workload finishes and before the Hosted Clusters are deleted to debug any problems identified through dashboards later. Collecting so many must-gathers on the jump host might not be possible - so we may need to send them over to some nfs share.

**Comment by smalleni** [comment]
@morenod @dry923 @mukrishn

**Comment by morenod** [comment]
I think we can save on local, it will add just 300M (30 if we compress) to the folder of each HC

311M	test_must_gather
30M	test.tar.gz
