### ISSUE TITLE
latest version of rosa cli requires to precreate the OIDC provider

### ISSUE THREAD

**Issue by morenod** [cloud-bulldozer/osde2e-scale-wrapper#131]
When executing rosa create cluster as we are doing now:

E: Hosted Control Plane requires an OIDC Configuration ID
Please run `rosa create oidc-config -h` and create one.

Now, we need to precreate it with

rosa create oidc-config -m auto --managed -y

and then add the ID returned as:

rosa create cluster --sts --oidc-config-id 22s4vf2v6f3ik2jei72qs2om3hnokm5p

**Comment by dry923** [comment]
Will be resolved in https://github.com/cloud-bulldozer/perfscale-managed-services/pull/129
