### ISSUE TITLE
Add parameter to select/override OCP version to use

### ISSUE THREAD

**Issue by morenod** [cloud-bulldozer/osde2e-scale-wrapper#25]

**Comment by dry923** [comment]
You can do this via the config file:

```
cluster:
  version: openshift-v4.5.13
```

**Comment by morenod** [comment]
Yes, but we need to find a way to override this value, so we can select the OCP version on the jobs.

We can do it overriding the value on the file with a parameter or creating a task on the job to manage this file.

If we do it with a task in the job, it will be only useful when executing from jenkins, if we override the parameter, we can also add some logic so we can use links like latest, latest-nightly, etc
