### ISSUE TITLE
Add option to download the kubeconfig after install

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/osde2e-scale-wrapper#28]
We should allow the user to have the kubeconfig automatically downloaded and saved to the cluster install path post install. This can be done via osde2ectl like:

```
$ ./out/osde2ectl --custom-config my_config.yaml get -k -i [my_cluster_id] --kube-config-path /my/test/path/cluster
```

**Comment by morenod** [comment]
Having problems to manage kubeconfig file downloading

https://github.com/openshift/osde2e/issues/657
