### ISSUE TITLE
Need to force account information to be passed as a string

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/osde2e-scale-wrapper#3]
When populating the 
ocm:
  aws:
    accessKey:
    account:
    secretKey:

we are not forcing surrounding ' 's. When it is then read by osde2e it is converted into an int and drops any leading 0.

**Comment by morenod** [comment]
Related to https://github.com/yaml/pyyaml/issues/98

I have moved to ruamel.yaml instead of pyyaml and now, all strings that could be considered numbers are quoted
