### ISSUE TITLE
Unique identifier on cluster names

### ISSUE THREAD

**Issue by morenod** [cloud-bulldozer/osde2e-scale-wrapper#5]
When creating clusters in a batch, all of them have the same name:

$ osde2e/out/osde2ectl list --custom-config custom_config.yaml
2020/11/19 12:14:44 Custom YAML config provided, loading from custom_config.yaml
NAME                     ID                                 STATE          STATUS                   OWNER                    INSTALLED VERSION        UPGRADE VERSION
morenod                  1h20e43ahroenhk414nd8gecet5ce6v1   pending        waiting-for-ready        dsanzmor                 openshift-v4.5.13
morenod                  1h20e4469vqf9s25e2kbohpv8qdru2kl   pending        waiting-for-ready        dsanzmor                 openshift-v4.5.13
morenod                  1h20e449genfgsg85as2c1p3ktct88aa   pending        waiting-for-ready        dsanzmor                 openshift-v4.5.13
morenod                  1h20e46v5lmkke8cl6lvo7jaau1skk6a   pending        waiting-for-ready        dsanzmor                 openshift-v4.5.13
morenod                  1h20e4et9rkrf9aedjd7m2ao7ghigtou   pending        waiting-for-ready        dsanzmor                 openshift-v4.5.13

**Comment by dry923** [comment]
@morenod what does your config file look like? I'm pretty certain I don't get the same name but id have to go back and check.

**Comment by morenod** [comment]
$ cat custom_config.yaml 
cloudProvider:
  providerId: aws
  region: xxxxx
cluster:
  version: openshift-v4.5.13
  name: "morenod"
ocm:
  env: stage
  token: xxxx
  userOverride: xxxx
  ccs: True
  aws:
    account: xxxxx
    accessKey: xxxx
    secretKey: xxxxx

**Comment by dry923** [comment]
ahhh yeah thats b/c you set the name. If you leave it blank it will create its own unique one.
```
name: "morenod"
```

**Comment by morenod** [comment]
Yes, verified, closing

**Comment by morenod** [comment]
Reopening, when selecting a name, we need to add  5-random chars to the cluster name selected, to unique identify installations
