### ISSUE TITLE
Include cluster identifiers in scale test console output

### ISSUE THREAD

**Issue by 2uasimojo** [cloud-bulldozer/osde2e-scale-wrapper#55]
It would be super helpful if log lines like this:

```
10:07:36 2021-02-04 16:08:09.334 INFO osde2e-wrapper - _build_cluster: Started cluster 455
```

...could provide some kind of cluster identifier, e.g.

```
10:07:36 2021-02-04 16:08:09.334 INFO osde2e-wrapper - _build_cluster: Started cluster 455: osde2e-1wxyz
```

I'm given to understand this may be nontrivial because the process that spits out that message spawns the cluster creation asynchronously. But hey, wanted to get the idea down.

**Comment by jtaleric** [comment]
if it is to somehow align cluster numeration with cluster-name, could we pass the cluster numeration down somehow as part of the cluster-name/uuid? somehow `osde2e-455-qwxyz`, that way it can stay async, and we can align the timings?

**Comment by 2uasimojo** [comment]
That would totally satisfy the ask, and then some. Sounds like it might be easier to implement as well.

**Comment by dry923** [comment]
Yeah it would be relatively simple to add a name creation to it and pass it into the config file. 

@morenod @chentex either of you want to take a look at doing this?

**Comment by morenod** [comment]
That is something I have already prepared for the rosa cli wrapper, I will adapt to osde2e and include

https://github.com/morenod/osde2e-scale-wrapper/blob/rosa_script/rosa/rosa-wrapper.py#L528

Cluster name is defined inside the creation function here

https://github.com/morenod/osde2e-scale-wrapper/blob/rosa_script/rosa/rosa-wrapper.py#L202

But I have all the required information before starting the function, so I will move it outside the function, to be available to put in the log line of the starting cluster creation

**Comment by jtaleric** [comment]
Nice stuff @morenod !!
