### ISSUE TITLE
Add test summary when testing is complete

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/osde2e-scale-wrapper#81]
When the test is done we simply get a 0|1 exit. We should provide a summarized output. Something as simple as running the watcher one last time before exiting would be a step in the right direction.

**Comment by chentex** [comment]
The problem I see with that is that the summary should have to run before the cleanup part, otherwise clusters will be already gone, unless I understand the watcher and the cleanup methods incorrectly.

**Comment by morenod** [comment]
which test are you referring to, @dry923?

Running tests after installing will be covered in the jenkins job, not during the installation. As @chentex mentions, we need to install clusters, run the tests and destroy them, so we need to PR about deleting clusters https://github.com/cloud-bulldozer/perfscale-managed-services/pull/76 and then, the PR for integrate tests on the jenkins job https://github.com/cloud-bulldozer/scale-ci-pipeline/pull/196

If we want a summarized output, I think we have to do it on the job

**Comment by dry923** [comment]
@morenod My thinking was just a final summary of the expected and resultant outcomes. For example if we did a scale test with 100 clusters at 5s delay then we should post something like:
```
Clusters requested: 100
Cluster delay: 5s
Cluster name seed: foo
Clusters successfully created: 85
Final cluster status:
ready: X
errored: Y
.....
```
The last bit could simply be a report out of the watcher again.

Thoughts?

**Comment by morenod** [comment]
ok ok, sorry, I was thinking on the tests after installation, not considering the installation as a test.

I need to check if we have all the required information about failures on the main thread, but yeah, we can create a summary with all the info we have

**Comment by dry923** [comment]
Yeah to @chentex 's point earlier we would need to make sure we grab the details before cleanup. So it might be a case where we need to closeout the watcher thread and grab that info somehow prior to cleanup.
