### ISSUE TITLE
Jenkins job cleans up cluster even when it is not specified

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/osde2e-scale-wrapper#84]
When running the osde2e scale test the Cluster cleanup box was unchecked yet the clusters were cleaned up anyway. See https://jenkins.scalelab.redhat.com/job/SCALE-CI-MS-OSDE2E/12/ for an example

**Comment by dry923** [comment]
cc @chentex @morenod

**Comment by morenod** [comment]
This was problably introduced after removing "is True" here https://github.com/cloud-bulldozer/perfscale-managed-services/pull/82/files#diff-b00512b305bddf9239d88a18b35005689c1ea31c9217e6f67386b7b7e04f9735L520

It will be fixed here https://github.com/cloud-bulldozer/perfscale-managed-services/pull/83/files#diff-d9221c824593436ccce0488ca4acb649af24d233a34b90ac63384cc3f270e7b2R478
